### ISSUE TITLE
Community contributions?

### ISSUE THREAD

**Issue by karllark** [radicamc/exoTEDRF#12]
As part of reviewing the joss paper (https://github.com/openjournals/joss-reviews/issues/6898) I did not see any guidelines for community contributions in the repository (or paper).  Are such possible and/or encouraged?  It would be good to have a clear statement of this in the README at a minimum.

**Comment by radicamc** [comment]
Added some text to this effect in the README and docs in [613a884](https://github.com/radicamc/exoTEDRF/commit/613a884129e93c6c36067f10a57a412dfa5f4b04).
