### ISSUE TITLE
Statement of Need in Documentation

### ISSUE THREAD

**Issue by karllark** [radicamc/exoTEDRF#13]
As part of reviewing the joss paper (https://github.com/openjournals/joss-reviews/issues/6898). there is no statement of need in the documentation.  There is one in the paper and I would recommend using that in the docs themselves to provide users with this information.  Would be good to state clearly in the docs why the jwst pipeline is not sufficient (for example).

**Comment by radicamc** [comment]
Addressed in [f1e9c70](https://github.com/radicamc/exoTEDRF/commit/f1e9c7095c73e3d6cb31a20aac98a6b3b0fd6c35).
